In [ ]:
import numpy as np
import pandas as pd
from util import *

%load_ext autoreload

In [ ]:
%reload_ext autoreload

## Run to generate train & test csv with features

In [3]:
train = pd.read_csv('../data/raw/train.csv')
test = pd.read_csv('../data/raw/test.csv')

In [4]:
train = process_basic(train)
test = process_basic(test)

In [5]:
train = process_flat_type(train)
test = process_flat_type(test)

In [6]:
comm = pd.read_csv("../data/processed/comm-dist-matrix.csv")
hawker = pd.read_csv("../data/processed/hawker-dist-matrix.csv")
mall = pd.read_csv("../data/processed/mall-dist-matrix.csv")
psch = pd.read_csv("../data/processed/psch-dist-matrix.csv")
ssch = pd.read_csv("../data/processed/ssch-dist-matrix.csv")
stations = pd.read_csv("../data/processed/stations-dist-matrix.csv")

In [7]:
test_comm = pd.read_csv("../data/processed/test-comm-dist-matrix.csv")
test_hawker = pd.read_csv("../data/processed/test-hawker-dist-matrix.csv")
test_mall = pd.read_csv("../data/processed/test-mall-dist-matrix.csv")
test_psch = pd.read_csv("../data/processed/test-psch-dist-matrix.csv")
test_ssch = pd.read_csv("../data/processed/test-ssch-dist-matrix.csv")
test_stations = pd.read_csv("../data/processed/test-stations-dist-matrix.csv")

## Point-of-interest integration

We take the distance to nearest POI instead of number of POI within

In [8]:
train['ssch_nearest_dist'] = ssch.drop(['Unnamed: 0'], axis=1).min(axis=1)
train['psch_nearest_dist'] = psch.drop(['Unnamed: 0'], axis=1).min(axis=1)
train['mall_nearest_dist'] = mall.drop(['Unnamed: 0'], axis=1).min(axis=1)
train['hawker_nearest_dist'] = hawker.drop(['Unnamed: 0'], axis=1).min(axis=1)
train['comm_nearest_dist'] = comm.drop(['Unnamed: 0'], axis=1).min(axis=1)
train['station_nearest_dist'] = stations.drop(['Unnamed: 0'], axis=1).min(axis=1)

In [9]:
test['ssch_nearest_dist'] = test_ssch.drop(['Unnamed: 0'], axis=1).min(axis=1)
test['psch_nearest_dist'] = test_psch.drop(['Unnamed: 0'], axis=1).min(axis=1)
test['mall_nearest_dist'] = test_mall.drop(['Unnamed: 0'], axis=1).min(axis=1)
test['hawker_nearest_dist'] = test_hawker.drop(['Unnamed: 0'], axis=1).min(axis=1)
test['comm_nearest_dist'] = test_comm.drop(['Unnamed: 0'], axis=1).min(axis=1)
test['station_nearest_dist'] = test_stations.drop(['Unnamed: 0'], axis=1).min(axis=1)

In [10]:
train = count_poi(train, ssch, 1, 'nbr_ssch_1k')
train = count_poi(train, psch, 1, 'nbr_psch_1k')
train = count_poi(train, mall, 1, 'nbr_mall_1k')
train = count_poi(train, hawker, 1, 'nbr_hawker_1k')
train = count_poi(train, comm, 1, 'nbr_comm_1k')
train = count_poi(train, stations, 1, 'nbr_station_1k')

In [11]:
test = count_poi(test, test_ssch, 1, 'nbr_ssch_1k')
test = count_poi(test, test_psch, 1, 'nbr_psch_1k')
test = count_poi(test, test_mall, 1, 'nbr_mall_1k')
test = count_poi(test, test_hawker, 1, 'nbr_hawker_1k')
test = count_poi(test, test_comm, 1, 'nbr_comm_1k')
test = count_poi(test, test_stations, 1, 'nbr_station_1k')

In [12]:
train = drop_cols(train)
test = drop_cols(test)

In [13]:
test

,floor_area_sqm,lease_duration,storey,flat_model_adjoined flat,flat_model_apartment,flat_model_dbss,flat_model_improved,flat_model_improved maisonette,flat_model_maisonette,flat_model_model a,...,mall_nearest_dist,hawker_nearest_dist,comm_nearest_dist,station_nearest_dist,nbr_ssch_1k,nbr_psch_1k,nbr_mall_1k,nbr_hawker_1k,nbr_comm_1k,nbr_station_1k
0,94.0,15,5.0,0,0,0,0,0,0,0,...,0.693506,0.792309,1.749017,0.667130,4,3,2,2,1,2
1,122.0,4,5.0,0,0,0,1,0,0,0,...,1.932765,2.069274,1.818631,1.832348,3,2,0,0,0,0
2,67.0,20,2.0,0,0,0,0,0,0,0,...,0.524283,0.787872,0.928551,0.517931,1,2,4,1,1,1
3,82.0,34,5.0,0,0,0,0,0,0,0,...,0.828608,0.957000,2.026039,0.546579,3,2,3,3,0,1
4,117.0,26,2.0,0,0,0,0,0,0,0,...,0.604285,0.112928,1.826417,0.515554,5,2,3,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107929,110.0,5,11.0,0,0,0,1,0,0,0,...,0.533432,0.732620,2.421703,1.555273,2,2,2,1,0,0
107930,102.0,7,14.0,0,0,0,0,0,0,1,...,0.906510,0.151803,2.592430,0.348201,0,0,1,3,0,1
107931,68.0,21,8.0,0,0,0,1,0,0,0,...,0.064781,0.688814,0.461844,0.292809,1,0,15,1,2,2
107932,104.0,21,11.0,0,0,0,0,0,0,1,...,1.107072,1.122422,1.126788,2.083779,1,2,0,0,0,0
107933,90.0,9,5.0,0,0,0,0,0,0,1,...,0.415591,1.905665,1.835184,0.415369,2,7,1,0,0,3

In [14]:
train

,floor_area_sqm,resale_price,lease_duration,storey,flat_model_adjoined flat,flat_model_apartment,flat_model_dbss,flat_model_improved,flat_model_improved maisonette,flat_model_maisonette,...,mall_nearest_dist,hawker_nearest_dist,comm_nearest_dist,station_nearest_dist,nbr_ssch_1k,nbr_psch_1k,nbr_mall_1k,nbr_hawker_1k,nbr_comm_1k,nbr_station_1k
0,118.0,209700.0,12,2.0,0,0,0,0,0,0,...,1.032567,0.944966,2.312122,1.136808,5,6,1,2,1,1
1,110.0,402300.0,11,11.0,0,0,0,1,0,0,...,0.805534,3.780019,1.461516,0.823036,6,8,4,0,0,2
2,112.0,351000.0,16,2.0,0,0,0,0,0,0,...,0.452272,1.802808,1.444013,2.229299,1,2,2,0,0,0
3,67.0,151200.0,20,8.0,0,0,0,0,0,0,...,0.456213,0.617904,2.385591,0.423055,2,2,3,2,0,1
4,73.0,318600.0,28,8.0,0,0,0,0,0,0,...,0.763692,0.761443,1.805955,0.773734,2,2,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431727,101.0,238500.0,5,2.0,0,0,0,0,0,0,...,0.201474,1.473613,1.039111,0.964207,3,5,2,0,0,1
431728,95.0,376200.0,4,14.0,0,0,0,0,0,0,...,0.191319,1.851253,1.607570,2.068516,1,2,3,0,0,0
431729,67.0,255600.0,25,2.0,0,0,0,0,0,0,...,0.767073,0.723587,1.223247,1.160647,3,4,1,1,0,0
431730,123.0,508500.0,14,17.0,0,0,0,1,0,0,...,0.480181,2.584299,1.624778,0.613543,4,5,3,0,0,2
431731,104.0,162000.0,18,2.0,0,0,0,0,0,0,...,0.380535,2.480030,4.184082,0.952735,2,3,2,0,0,1

In [17]:
train.to_csv("../data/processed/train.csv")

In [18]:
test.to_csv("../data/processed/test.csv")